layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 13
  exclude:
    archived: true
    forks: true
    projects:
      - observatory

social_media:
  website: http://jhermann.github.io/
  gitlab: jhermann
  devto: jhermann
  stackoverflow: 2748717
  twitter: jhermann_
  meetup: 209463925
  goodreads: 33445630
  linkedin: jürgen-hermann-de
  # behance: your_username
  # devto: your_username
  # dribbble: your_username
  # facebook: your_username
  # gitlab: your_username
  # goodreads: your_user_id
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # meetup: your_user_id
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python3
    web_url: https://planetpython.org/
    image_url: https://jhermann.github.io/about-me/assets/img/logo-python.svg

  - name: Data Science
    web_url: https://towardsdatascience.com/
    image_url: https://jhermann.github.io/about-me/assets/img/logo-data-science.svg

  - name: Jupyter Notebook
    web_url: https://github.com/jhermann/jupyter-by-example#readme
    image_url: https://jhermann.github.io/about-me/assets/img/logo-jupyter.svg

  - name: DevOps
    web_url: https://devops.com/
    image_url: https://jhermann.github.io/about-me/assets/img/logo-devops.svg

  - name: Linux
    web_url: https://www.linuxfoundation.org/
    image_url: https://jhermann.github.io/about-me/assets/img/logo-linux.svg

  - name: Writing
    web_url: https://www.writethedocs.org/
    image_url: https://jhermann.github.io/about-me/assets/img/logo-writing.svg

